channels:
    - defaults
      
dependencies:
    - python=3.6
    - sphinx
    - sphinx_rtd_theme
    - pip
    - enaml
    - bcolz
    - numpy
    - palettable
    - pyqtgraph
    - scipy
    - pip:
        - pygments-enaml
        - json_tricks
        - git+https://github.com/bburan/psiexperiment.git
